### ISSUE TITLE
wsgi application connection error

### ISSUE THREAD

**Issue by Vidul08** [Devdynamo-Ayush/ChatBuddy#3]
zeeps

**Comment by Pratik-Pandit** [comment]
pip install django-cors-headers==3.8.0
pip install djangorestframework==3.12.4

**Comment by Pratik-Pandit** [comment]
import os

from django.core.wsgi import get_wsgi_application

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'studybud.settings')

application = get_wsgi_application()
